name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Prod
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - id: Auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/1058747850311/locations/global/workloadIdentityPools/github/providers/github-tnguyen14
          service_account: github-actions@build-tridnguyen-com.iam.gserviceaccount.com

      - name: Deploy CloudRun
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: sheets
          source: .
          region: us-central1
